// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzdngeaakfxjjspebpzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6ZG5nZWFha2Z4ampzcGVicHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzMwODAsImV4cCI6MjA2NDcwOTA4MH0.iX60sdugD9RQRKEoTncJ3HEjmnYsVM5EKUANT7Vsn7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);